# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Morisy's Instant History
email: m@morisy.com
description: >
  Michael Morisy's long-running (with many long rests) blog on media and technology.
logo: "/assets/images/logo.GIF"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://morisy.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Michael Morisy'
bio: >
  Michael Morisy is the founder of MuckRock
author_image: "/assets/images/candid.jpg"
twitter_username: morisy
github_username:  morisy

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
